### PR TITLE
Override quadgk deprecation in Base

### LINKED ISSUE #8: Misleading deprecation advice
When you follow the deprecation advice for using this package on Julia 0.6 and beyond,

```
julia> quadgk()
ERROR: quadgk() has been moved to the package QuadGK.jl.
Run Pkg.add("QuadGK") to install QuadGK on Julia v0.6 and later, and then run `using QuadGK`.
```

It does not actually work due to a clash with the deprecation warning itself.

```
julia> using QuadGK
julia> quadgk()
WARNING: both QuadGK and Base export "quadgk"; uses of it in module Main must be qualified
ERROR: UndefVarError: quadgk not defined
```

I believe the above was working on MASTER sometime over Winter 2016 / Spring 2017, as I had added `using QuadGK` to all my codes to make the deprecation warning go away!

Instead you must import the function(s) you want explicitly,
```
julia> import QuadGK.quadgk
julia> quadgk
quadgk (generic function with 3 methods)
```

Or reference the QuadGK package every time you call the function,
```
julia> using QuadGK
julia> QuadGK.quadgk
quadgk (generic function with 3 methods)
```

See also discussion at: 
https://github.com/JuliaLang/julia/pull/19741

Can the QuadGK functions be forcibly exported into the namespace when the packaged is `using`'d ? That would seem to be the expected behaviour by the user.

### PR DESCRIPTION
**Pull request by carlobaldassi**
Fixes #8, e.g. on julia 0.6:

```
julia-0.6> using QuadGK

julia-0.6> quadgk(sin, 0, 1)
(0.4596976941318603, 5.551115123125783e-17)
```

On julia 0.4 and 0.5, the same code will use the version from `Base`, unless calls to `quadgk` are qualified explicitly.

This should ensure a smooth transition.

I used [this commit](https://github.com/JuliaLang/julia/commit/dbbd7e510d54810071d81acfd849e657bbb36dbd) for computing the julia version.

This also adds julia 0.6 to the Travis tests.

### CODE REVIEW

**Comment by stevengj** [comment]
This is the wrong thing in 0.7, so it needs another version check. See how SpecialFunctions does it.

**Comment by carlobaldassi** [comment]
Thanks, should be fixed now (tested on latest master). I have added the PR numbers in a comment.

**Comment by carlobaldassi** [comment]
The failure on nightly OS X is a simple download problem, it should be fixed by restarting [the job](https://travis-ci.org/JuliaMath/QuadGK.jl/jobs/259808221).

**Comment by ararslan** [comment]
Job restarted

**Pull request merged**
